"""TokenHarbor provider profile — one key, every model (OpenAI-compatible)."""

from providers import register_provider
from providers.base import ProviderProfile

tokenharbor = ProviderProfile(
    name="tokenharbor",
    env_vars=("TOKENHARBOR_API_KEY",),
    display_name="TokenHarbor",
    description="TokenHarbor — one key, every model",
    signup_url="https://tokenharbor.ai/dashboard/api-keys",
    base_url="https://tokenharbor.ai/v1",
    fallback_models=(
        "th-orchestra",
        "claude-sonnet-4.6",
        "claude-opus-5",
        "claude-sonnet-5",
        "grok-4.6",
        "glm-5.3",
        "kimi-k3",
        "kimi-k2.6",
        "mimo-v2.5-pro",
        "mimo-v2.5",
        "gemini-3.8-flash",
        "deepseek-v4-flash",
        "claude-fable-5.1",
        "qwen3.7-max",
        "glm-5.1",
        "deepseek-v4-pro",
        "claude-fable-5",
        "claude-opus-4.8",
        "gpt-5.5",
        "qwen3.8-max",
        "glm-5.3-flash",
        "gemini-3.7-flash",
        "grok-4.5",
        "muse-spark-1.2",
        "muse-spark-1-3",
        "gpt-6-astra",
        "deepseek-v4.1-flash",
        "gemini-3.6-flash",
        "glm-5.2",
        "gpt-5.6-luna",
        "gpt-5.6-sol",
        "gpt-5.6-terra",
        "muse-spark-1.1",
        "qwen3.6-27b",
        "qwen3.6-flash",
        "deepseek-v3.2",
        "qwen3.5-27b",
        "qwen3.7-flash",
        "qwen3.8-27b",
        "qwen3.8-flash",
        "claude-opus-5-fast",
        "kimi-k3-fast",
        "gpt-5.6-luna-fast",
        "gpt-5.6-sol-fast",
        "gpt-5.6-terra-fast",
        "gpt-6-astra-fast",
        "glm-5.3-fast",
        "glm-5.3-flashx",
        "mimo-v2.5:free",
        "deepseek-v4-flash:free",
        "deepseek-v4.1-flash:free",
        "qwen3.8-flash:free",
    ),
)

register_provider(tokenharbor)
